### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-react-prototype#69]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by rsimha** [comment]
@jridgewell @dvoytenko I checked and noticed this repo contains no hard-coded references to the default branch. Happy to do the renaming if you'd like.

**Comment by jridgewell** [comment]
This repo is effectively just an archive, so we can rename without any issues.

**Comment by jridgewell** [comment]
I don't have admin permissions, so you'll need to do it.

**Comment by rsimha** [comment]
Done.

![image](https://user-images.githubusercontent.com/26553114/115768871-df23cb00-a378-11eb-90e3-d0a12e0db60e.png)
